### ISSUE TITLE
Better tests for lesson 1 (sortAddresses)

### ISSUE THREAD

**Issue by mglukhikh** [Kotlin-Polytech/Algorithms#16]

**Comment by mglukhikh** [comment]
May be taken e.g. from here: http://kotoed.icc.spbstu.ru:9000/submission/9221

**Comment by AbdullinAM** [comment]
650452e8037c267e2af7a42ceb64a07df79d31de
Еще один тест на ~50000 входных строк

**Comment by AbdullinAM** [comment]
5ebca10bc4d706dbeed08d6e1a23d693dad83fbb
