### ISSUE TITLE
Уточнение в слайдах про MAX-HEAPIFY

### ISSUE THREAD

**Issue by gagarski** [Kotlin-Polytech/Algorithms#7]
В презентации 02_Sorting.pdf на слайде 25 возможно требуется уточнение: вместо "один из корней поддеревьев" написать "больший из корней поддеревьев", а вместо "для одного из поддеревьев" &mdash; "для поддерева с большим корнем". Псевдокод на следующем слайде правильный и обеспечивает выбор нужного поддерева.

**Comment by mglukhikh** [comment]
Поправил в локальной (пока не выложенной) версии слайдов для 2018 года. Из репозитория слайды убраны.
